--- #YAML:1.0
name: Widget-Meta
version: 0.03
author:
  - David Wheeler <david@kineticode.com>
abstract: Metadata for user interface widgets
license: perl
build_requires:
  Test::Simple: 0.17
provides:
  Widget::Meta:
    file: lib/Widget/Meta.pm
    version: 0.03
generated_by: Module::Build version 0.25_03
