---
name: Widget-Meta
version: 0.04
author:
  - 'David Wheeler <david@kineticode.com>'
abstract: Metadata for user interface widgets
license: perl
resources:
  license: http://dev.perl.org/licenses/
configure_requires:
  Module::Build: 0.2701
build_requires:
  Module::Build: 0.2701
  Test::More: 0.17
recommends:
  Test::Pod: 1.20
provides:
  Widget::Meta:
    file: lib/Widget/Meta.pm
    version: 0.04
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
